### ISSUE TITLE
callbacks don't pass instance

### ISSUE THREAD

**Issue by brianwebb01** [laravelbook/ardent#104]
\Laravelbook\Ardent\Ardent.php:232  When the callback is called the instance is not passed, however the instance should be passed by default.

So:

    return $model->$method();

should be

    return $model->$method($model);

**Comment by igorsantos07** [comment]
Seems fixed now?

https://github.com/laravelbook/ardent/blob/master/src/LaravelBook/Ardent/Ardent.php#L242
