### ISSUE TITLE
LocalKey not working with a HAS_ONE relationship

### ISSUE THREAD

**Issue by MrAtiebatie** [laravelbook/ardent#204]
I had the following database scheme:

### users
- id
- name
- language_id

### languages
- id
- name

Now I have tried to make the relationship between language_id and languages.id:
![ardent1](https://cloud.githubusercontent.com/assets/2266552/2907237/f66dd744-d619-11e3-8c21-425d371e4f75.PNG)

![ardent2](https://cloud.githubusercontent.com/assets/2266552/2907241/009e9820-d61a-11e3-9768-57205ae67245.PNG)

But after an hour debugging I found out that he didn't used the localKey but just the primary key of the table, in the case of the user table it's 'id'. So I took a look in the source of Ardent and saw that the localKey parameter isn't sent to Model@hasOne while it is an (optional) parameter of the hasOne method of Laravel. Is this a bug? Because when I changed rule __316&317__ in Ardent.php it worked:
![ardent3](https://cloud.githubusercontent.com/assets/2266552/2920288/b503826a-d6e4-11e3-80d7-7d387b7e5403.PNG)

Thanks in advance

**Comment by misilot** [comment]
What would need to be done to get this included in a release?

**Comment by gg4you** [comment]
Has this been included in a release?

**Comment by igorsantos07** [comment]
It will be in the next week!

Igor Santos
-- Desenvolvedor Web
[enviado do meu celular]

**Comment by igorsantos07** [comment]
this might be something that was added later and not looked into at the time of development.

Just wondering: is your field was `language_id` why is the local key only `language`? haha
