### ISSUE TITLE
Laravel 4.2 soft delete doesn't work with Ardent

### ISSUE THREAD

**Issue by IntellectProductions** [laravelbook/ardent#211]
Ok so Laravel 4.1 with the protected $softDelete = true works fine with Ardent. But when you upgrade to Laravel 4.2, it doesn't work anymore since they changed the way soft delete is set. It will still remove the record, but it will remove it permanently instead of updating the deleted_at column.. Do you know when there will be a fix for this?

http://laravel.com/docs/upgrade#upgrade-4.2

Thanks!

**Comment by igorsantos07** [comment]
This is being looked at. If there's still someone here, please lend me a hand at #227.
The original maintainer abandoned the project almost completely, and I tried to hold it, but I don't have enough time to look at it, besides health issues. I'm trying to catch up, as the package still have a lot of daily downloads.

**Comment by chriskonnertz** [comment]
I don't know if https://github.com/mspivak/ardent/commit/19d231e7dc3e42e0a8c8482479f5fe724dc4f9b1 solves the problem or not. I do use my own fork of Ardent. Therefore I cannot test the change. But it looks promising.

**Comment by thinksaydo** [comment]
thanks @chriskonnertz. you are correct. @mspivak commit fixed this issue for us for an older Laravel 4.2 project. his other commit also fixed the morphTo issue. cc @igorsantos07

**Comment by igorsantos07** [comment]
Thanks for the followup, @chriskonnertz and @thinksaydo. Would you please help me review the PR #227? Specifically this [part here](https://github.com/laravelbook/ardent/pull/227#discussion_r29998763). That seems quite odd to me.
With that solved I'll merge and create a new release - that's already in draft, just waiting for those bigger issues to be solved.

**Comment by chriskonnertz** [comment]
Honestly I am very disappointed by Ardent. I had to fix the bug myself and I had to create a very dirty fork. The only way that I could help you is to merge the changes of the PR into my fork and I am not going to do that. I do not want to risk that. I do not trust Ardent any more and therefore I do not plan to use it again.

**Comment by chriskonnertz** [comment]
Look at https://github.com/mspivak/ardent/blob/9fbe73399d84fc726dc9e122955de444f4fb4901/src/LaravelBook/Ardent/Ardent.php line 428 there it is using belongTo. So I guess here in https://github.com/mspivak/ardent/commit/1228dfe7eee662fa0b41a34aa82212ce9b7b0f62 the red line are just something left over from July 2014. It should not change anything if you merge it.

**Comment by chriskonnertz** [comment]
I believe you can accept the PR. Or refuse it and create a new PR by yourself. Because essentially all it does is to update the newQuery() method so that it does not use old soft deleting stuff any more.

I have created a new PR without the strange part ( https://github.com/laravelbook/ardent/pull/227#discussion_r29998763 ) of the old one: https://github.com/laravelbook/ardent/pull/269

**Comment by igorsantos07** [comment]
I'm going to accept your new PR, @chriskonnertz. 
I'm sorry for your disappointment, but I'm doing my best at this side. I can feel your pain as I was feeling the same when I decided to work on the repository myself... Sadly, the owner felt of the face of the earth and I got no control over some parts of the project - like the Github Page or Composer package.
I'm trying to catch up. If you still are dependant on Ardent - or your own fork - and are willing to help, I'll be glad to see you here again. You can PR new things you've done if you feel OSS-y :)

**Comment by igorsantos07** [comment]
I've merged your PR directly as, per other discussions, that seems to be the fix.
Investigating a little bit more it seems that weird part was actually a fix for another creepy bug that wasn't noticed - and @mspivak fixed it without citing explicitly. Gonna open a new issue to investigate it.

**Comment by chriskonnertz** [comment]
Ok.

**Comment by MrNomNom** [comment]
damn. This PR broke my app... :) Looks like on 4.1 this change creates infinite loop of dependancy injections. Will investigate for more details...
