### ISSUE TITLE
HHVM support?

### ISSUE THREAD

**Issue by milesj** [laravelbook/ardent#256]
It seems like Ardent is completely broken because of lines like this:

https://github.com/laravelbook/ardent/blob/master/src/LaravelBook/Ardent/Ardent.php#L376

HHVM returns a different structure for `debug_backtrace()` as it doesn't return magic calls.

Issue in question: https://github.com/facebook/hhvm/issues/1944

**Comment by milesj** [comment]
Bump.

**Comment by igorsantos07** [comment]
well, it seems by that issue they intentionally broke compatibility with the Zend implementation?
if that's the case, I'm not sure what to do here. Would need to take a deeper look in the code and, maybe, even create a split there between PHP implementations - and I'm not sure this is good.

I would accept PRs on this, though :)

**Comment by milesj** [comment]
IMO, you shouldn't be using `debug_backtrace()` in application code. Shouldn't Ardent be able to use `__call()`? Or is there some Laravel reason that's not possible.

**Comment by igorsantos07** [comment]
Take a look here: https://github.com/illuminate/database/blob/master/Eloquent/Model.php#L785

This is actually only an override to allow for Ardent's intelligent properties.
I guess you should ask for HHVM support to Eloquent first, not us :)
