### ISSUE TITLE
We need Laravel 5 support!!

### ISSUE THREAD

**Issue by canfiax** [laravelbook/ardent#260]
Whats up with this? Are you planning to support Laravel 5? Currently composer install fails.

**Comment by icedfish** [comment]
I want to known, if the dev team have any plan to support laravel 5?

**Comment by GrahamCampbell** [comment]
Ardent looks unmaintained to me. Go and look elsewhere.

**Comment by icedfish** [comment]
@igorsantos07  are you still maintaining this repo ?  Here is a lot of pull request pending there.
@laravelbook seems to be not working for more than 1 year.

**Comment by igorsantos07** [comment]
Sorry men.
I have a desire for maintaining this but as I'm not actively using the
project I had to cope with other professional and academic duties. That
plus professional health issues put me away from the project :(

However I'll be adding some people that offered help here!
And try to take some time to take a look at the PRs. Initially I was
worried with code quality and left them to be reviewed later, but that
later never came, so... I'll be accepting what makes sense.

Sorry!

Igor Santos
-- Desenvolvedor Web
[enviado do meu celular]

**Comment by mvdstam** [comment]
Thank you Igor, I hope things work out for you. Let's keep this repo alive, since it's a really (*really*) great package.

**Comment by azizgithub** [comment]
I am try to fork this repo and just change the require for iluminate to version : 5  (because i think eloquent model in laravel 5 similar to laravel 4).. but i am not sure for this.. what do you think its work Igor ?

**Comment by igorsantos07** [comment]
I'm going to clean up this repository this weekend or at most, during the
following week.
The last weekend I spent working in stuff even more delayed, a Faker PR. So
next step is Ardent.

If you want, create a PR, I'll take a look on it and release as a new
version, so only those imprudently using * as version will receive :)

Igor Santos
-- Desenvolvedor Web
[enviado do meu celular]

**Comment by azizgithub** [comment]
hay @igorsantos07 , that already exist PR for that https://github.com/laravelbook/ardent/pull/261 
and i am also PR again https://github.com/laravelbook/ardent/pull/263 please merge it..
and i am sorry because i released it to my packagist https://packagist.org/packages/aziz/smartmodel
because i am hurried to use it., :D

**Comment by igorsantos07** [comment]
Not a big deal, as long it doesn't cause a division (as long this package
get back to maintenance as well, of course)

Igor Santos
-- Desenvolvedor Web
[enviado do meu celular]

**Comment by azizgithub** [comment]
I am very sorry @igorsantos07 .. as soon as possible  i will to remove my
packagist.. and i hope this package as soon as possible release new version
that we request to support laravel 5.. :)
Pada 28 Mar 2015 12.28, "Igor Santos" <notifications@github.com> menulis:

> Not a big deal, as long it doesn't cause a division (as long this package
> get back to maintenance as well, of course)
>
> Igor Santos
> -- Desenvolvedor Web
> [enviado do meu celular]

**Comment by azizgithub** [comment]
@igorsantos07 my packagist has been removed :).. now wait for your new
release.. :)
Pada 28 Mar 2015 13.35, "muh aziz Nugroho" <kickaziz@gmail.com> menulis:

> I am very sorry @igorsantos07 .. as soon as possible  i will to remove my
> packagist.. and i hope this package as soon as possible release new version
> that we request to support laravel 5.. :)
> Pada 28 Mar 2015 12.28, "Igor Santos" <notifications@github.com> menulis:
>
>> Not a big deal, as long it doesn't cause a division (as long this package
>> get back to maintenance as well, of course)
>>
>> Igor Santos
>> -- Desenvolvedor Web
>> [enviado do meu celular]

**Comment by igorsantos07** [comment]
@azizgithub I would also advise you to not release cloned packages to packagist. You can use your forked code and still maintain the original library reference. Take a look at the [Composer docs on custom packages](https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository).

**Comment by igorsantos07** [comment]
Closing this issue as the subject may be discussed in #261, for cleanliness.

**Comment by azizgithub** [comment]
"You can use your forked code and still maintain the original library
reference"..
I am sorry i dont understand it because i am newbie in packagist., how can
i do to use ardent in laravel 5 instead to release my fork., thanks.,

2015-05-10 1:55 GMT+07:00 Igor Santos <notifications@github.com>:

> @azizgithub <https://github.com/azizgithub> I would also advise you to
> not release cloned packages to packagist. You can use your forked code and
> still maintain the original library reference. Take a look at the Composer
> docs on custom packages
> <https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laravelbook/ardent/issues/260#issuecomment-100529898>.
>



-- 

*Best Regards **[Muh Aziz* *Nugroho*]

**Comment by davincho** [comment]
@azizgithub by following the instructions from https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository you would have to do two things:

1. Create a branch in your repo (https://github.com/azizgithub/ardent) prefixed with ``dev`` like ``dev-laravel5.0``
2. Change your composer.json like so:

``
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/azizgithub/ardent"
        }
    ],
    "require": {
        "laravelbook/ardent": "dev-laravel5.0"
    }
}

``

Now, there is no need to register your forked project separately in packagist and composer automatically retrieves the dependency from your repo.
